on:
  pull_request:
  push:
    branches: "main"
    
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test CDK Stacks
        run: pwd
        working-directory: iac
      
